import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { PackageLists, default as packageLists } from "../lib/lists";

type Props = {
  lists: PackageLists;
};

const Page: NextPage<Props> = ({ lists }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Barnard59</h1>
        <p>Create nice pipelines</p>
        <Link href="/package" passHref>
          <Button variant="contained" size="large">
            Browse packages
          </Button>
        </Link>
      </main>
    </div>
  );
};

export async function getStaticProps(_context: any) {
  return {
    props: {
      lists: packageLists,
    }, // will be passed to the page component as props
  };
}

export default Page;
